version: "3.8"

services:
  web:
    image: docker.io/library/nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - web-public

networks:
  web-public:
    external: true